#!/bin/bash

TITLE="System information report for $HOSTNAME"
CURRENT_TIME=$(date +"%x %r %Z")
TIMESTAMP="Generated $CURRENT_TIME, by $USER"

echo "<html>
	<head>
		<TITTLE>$TITLE</TITLE>
	</head>
	<body>
		<H1>$TITLE</H1>
		<P>$TIMESTAMP</P>
	</body>
</html>"
